import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { api, type StudentProgress } from "../../lib/api";
import { Button, Spinner, Meter } from "../../components/ui";

// Print-friendly progress report. "Save as PDF" uses the browser print dialog
// against the print stylesheet, so the PDF can't drift from what's on screen.
export function ParentReport() {
  const { studentId = "" } = useParams();
  const [p, setP] = useState<StudentProgress | null>(null);

  useEffect(() => {
    if (studentId) api.studentProgress(studentId).then(setP);
  }, [studentId]);

  if (!p) return <div className="flex justify-center py-24"><Spinner /></div>;

  const best = [...p.subject_averages].sort((a, b) => b.average - a.average)[0];
  const focus = [...p.subject_averages].sort((a, b) => a.average - b.average)[0];
  const first = p.student_name.split(" ")[0];
  const today = new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });

  return (
    <div>
      <div className="mb-4 flex items-center justify-between print:hidden">
        <Link to="/parent" className="text-sm font-semibold text-brand-ink hover:underline">← Back</Link>
        <Button onClick={() => window.print()}>🖨️ Save as PDF</Button>
      </div>

      <div className="mx-auto max-w-3xl rounded-2xl border border-line bg-white p-10 shadow-card print:border-0 print:shadow-none">
        <div className="flex items-center justify-between border-b border-line pb-4">
          <div className="flex items-center gap-2">
            <span className="text-2xl">📓</span>
            <span className="font-display text-lg font-bold text-ink">Homework Studio</span>
          </div>
          <div className="text-xs text-ink-soft">Progress report · {today}</div>
        </div>

        <h1 className="mt-6 font-display text-3xl font-bold text-ink">{p.student_name}</h1>
        <p className="text-sm text-ink-soft">{p.grade_level}</p>

        <p className="mt-5 leading-relaxed text-ink">
          {first} has completed <b>{p.timeline.length}</b> homework{p.timeline.length === 1 ? "" : "s"} with an overall
          average of <b>{p.overall_average.toFixed(0)}%</b>.
          {best && ` Strongest in ${best.subject} (${best.average.toFixed(0)}%).`}
          {focus && best && focus.subject !== best.subject && ` A good area to keep practising is ${focus.subject}.`} Keep
          up the great effort! 🌟
        </p>

        <div className="mt-6 grid grid-cols-3 gap-4">
          {[
            { v: `${p.overall_average.toFixed(0)}%`, l: "Overall average", c: "text-brand-ink" },
            { v: `${p.timeline.length}`, l: "Homeworks done", c: "text-grow" },
            { v: best ? best.subject : "—", l: "Top subject", c: "text-ink" },
          ].map((s) => (
            <div key={s.l} className="rounded-xl bg-paper p-4 text-center">
              <div className={`font-display text-2xl font-bold ${s.c}`}>{s.v}</div>
              <div className="text-xs text-ink-soft">{s.l}</div>
            </div>
          ))}
        </div>

        <h2 className="mb-2 mt-8 text-lg font-semibold text-ink">By subject</h2>
        <div className="space-y-3">
          {p.subject_averages.map((s) => (
            <div key={s.subject}>
              <div className="mb-1 flex justify-between text-sm">
                <span className="font-semibold text-ink">{s.subject}</span>
                <span className="text-ink-soft">{s.average.toFixed(0)}%</span>
              </div>
              <Meter value={s.average} color={s.color} />
            </div>
          ))}
        </div>

        <h2 className="mb-2 mt-8 text-lg font-semibold text-ink">Homework history</h2>
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-line text-left text-ink-soft">
              <th className="py-1 font-medium">Date</th><th className="font-medium">Title</th><th className="font-medium">Subject</th><th className="text-right font-medium">Score</th>
            </tr>
          </thead>
          <tbody>
            {p.timeline.map((t) => (
              <tr key={t.homework_id} className="border-b border-line/60">
                <td className="py-1.5 text-ink-soft">{t.date}</td>
                <td className="text-ink">{t.title}</td>
                <td className="text-ink-soft">{t.subject}</td>
                <td className="text-right font-semibold text-ink">{t.percent.toFixed(0)}%</td>
              </tr>
            ))}
          </tbody>
        </table>

        <p className="mt-8 border-t border-line pt-4 text-xs text-ink-soft">
          Generated by Homework Studio. Independent portfolio demo with synthetic data.
        </p>
      </div>
    </div>
  );
}
